branches:
  except:
    - travis

language: java

jdk:
- openjdk8
#- openjdk10
#- openjdk11
#- openjdk12  

env:
- BUILD_TYPE=snapshot/$TRAVIS_BRANCH

script:
 - mvn install jacoco:report coveralls:report -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: 1.0.x
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      tags: true
