branches:
  except:
    - travis
language: java
jdk:
- openjdk8
env:
- BUILD_TYPE=snapshot
before_install:
- ./scripts/before-install.sh
install:
  - mvn install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script:
# - mvn test jacoco:report coveralls:report -Dgpg.skip -Dmaven.javadoc.skip=true -B
 - mvn test -Dgpg.skip -Dmaven.javadoc.skip=true -B
deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: 1.0.x
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      tags: true
notifications:
  slack: cloudfoundry:xvgjKLNQTyqAFMnsTywVHik9
