branches:
  except:
    - travis

language: java

jdk:
- openjdk8
#- openjdk10
#- openjdk11
#- openjdk12  

env:
- BUILD_TYPE=snapshot/$TRAVIS_BRANCH

before_install:
- docker pull exoplatform/sqlserver:2017-CU8
- docker run -d -e SA_PASSWORD=5F4Dt9ky9dU$ -e SQLSERVER_DATABASE=sc -e SQLSERVER_USER=user -e SQLSERVER_PASSWORD=5F4Dt9ky9dU$ -p 1433:1433 exoplatform/sqlserver:2017-CU8
#- curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
#- curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | sudo tee /etc/apt/sources.list.d/msprod.list
#- sudo apt-get update
#- sudo ACCEPT_EULA=Y apt-get install mssql-tools unixodbc-dev -y
#- /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P '5F4Dt9ky9dU$'

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
 - mvn -P tests install jacoco:report coveralls:report -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: 1.0.x
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      tags: true
