branches:
  except:
    - travis

language: java

jdk:
- openjdk8
#- openjdk10
#- openjdk11
#- openjdk12  

env:
- BUILD_TYPE=snapshot/$TRAVIS_BRANCH

before_install:
- docker pull exoplatform/sqlserver:2017-CU8
- docker run -d -e SA_PASSWORD=pass -e SQLSERVER_DATABASE=sc -e SQLSERVER_USER=user -e SQLSERVER_PASSWORD=pass -p 1433:1433 exoplatform/sqlserver:2017-CU8
- docker ps -a

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
 - mvn -P tests install jacoco:report coveralls:report -Dgpg.skip -Dmaven.javadoc.skip=true -B -V

deploy:
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: master
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      branch: 1.0.x
  - provider: script
    script: scripts/deploy.sh
    skip_cleanup: true
    on:
      repo: paulcwarren/spring-content
      tags: true
