# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ 1.2.x ]
  pull_request:
    branches: [ 1.2.x ]

jobs:

  build:

    runs-on: ubuntu-latest

    services:
      sqlserver: 
        image: exoplatform/sqlserver:2017-CU8
        env:
          SA_PASSWORD: 5F4Dt9ky9dU$
          SQLSERVER_DATABASE: sc
          SQLSERVER_USER: user
          SQLSERVER_PASSWORD: 5F4Dt9ky9dU$
        ports:
          - 1433:1433
      postgres:
        image: postgres:12.1
        env:
          POSTGRES_PASSWORD: 5F4Dt9ky9dU$ 
        ports:
          - 5432:5432
      mysql:
        image: mysql:8.0.19
        env:
          MYSQL_ROOT_PASSWORD: 5F4Dt9ky9dU$
          MYSQL_DATABASE: sc
        ports:
          - 3306:3306 
      elasticsearch:
        image: paulcwarren/elasticsearch:7.6.2
        env:
          discovery.type: single-node
        ports:
          - 9200:9200
          - 9300:9300
      solr:
        image: paulcwarren/solr 
        ports:
          - 8983:8983 

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B -P tests install --file pom.xml
      env:
        SQLSERVER_DB_NAME: "sc"
        SQLSERVER_HOST: "localhost:1433"
        SQLSERVER_PASSWORD: "5F4Dt9ky9dU$"
        SQLSERVER_USERNAME: "sa"
