name: PR Validation

on:
  pull_request:
    branches: [ 1.1.x,1.2.x ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        path: spring-content
    - uses: actions/checkout@v2
      with:
        repository: paulcwarren/spring-content-examples
        path: spring-content-examples
        ref: refs/heads/1.2.x
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: ossrh
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
        gpg-passphrase: MAVEN_GPG_PASSPHRASE
        
    - name: Build and test
      run: |
        pushd spring-content
          mvn -B -P tests -Dmaven.javadoc.skip=true install --file pom.xml
        popd

    - name: Validate examples
      run: |
        pushd spring-content-examples
          mvn -B clean install
        popd
