name: Java CI with Maven

on:
  push:
    branches: [ test-docs-publish ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    
    - name: Publish with Maven
      run: |
        set -eu

        if [[ "$GITHUB_REF" == *"tags"* ]]; then
            TAG=${GITHUB_REF#refs/tags/}
            BUILD_TYPE=release/"${TAG}""
            mvn org.codehaus.mojo:versions-maven-plugin:2.1:set -DnewVersion="${TAG}"
        else
            BUILD_TYPE=snapshot/${GITHUB_REF#refs/heads/}
        fi

        mvn -B -U -P docs generate-resources -DskipTests=true -Dmaven.javadoc.skip=true

        ssh-add - <<< "${secrets.CI_PRIVATE_KEY}"

        git config --global user.email ${CI_EMAIL}
        git config --global user.name ${CI_USERNAME}

        mkdir -p /tmp/spring-content-gh-pages
        git clone --branch gh-pages https://github.com/paulcwarren/spring-content /tmp/spring-content-gh-pages

        cp -R target/generated-docs/refs/* /tmp/spring-content-gh-pages/refs/

        pushd /tmp/spring-content-gh-pages
            git add .
            git commit -m "Publishing reference guides for ${GITHUB_REF}"
            git push
        popd
      env:
        CI_USERNAME: ${{ secrets.CI_USERNAME }}
        CI_PASSWORD: ${{ secrets.CI_PASSWORD }}
        CI_EMAIL: ${{ secrets.CI_EMAIL }}
        CI_PRIVATE_KEY: ${{ secrets.CI_PRIVATE_KEY }}
